/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-01 08:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("    \t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Top.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"d-flex align-items-stretch\">\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Left.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"page-holder w-100 d-flex flex-wrap\">\r\n");
      out.write("        <div class=\"container-fluid px-xl-5\">\r\n");
      out.write("        \t<section id = \"main\" class=\"section-padding\">\r\n");
      out.write("        \t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								String id = null;
								id = (String)session.getAttribute("userid");
									
								if ( id == null){ //회원이면
									out.print("방문을 환영합니다 :)<br>회원가입  또는 로그인 후 이용바랍니다!");
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("        \r\n");
      out.write("        \t<section id=\"member\" class=\"section-padding\">\r\n");
      out.write("        \t\t<div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("\t\t            <div class=\"row\">\r\n");
      out.write("\t\t                <div class=\"col-md-12 text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>TEAM_1</h2>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t                       \r\n");
      out.write("\t\t            <div class=\"row\">\r\n");
      out.write("\t\t                <div class=\"col-md-12 text-center inner-padding\">\r\n");
      out.write("\t\t                \t<div class=\"row\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t                       \t<span>GM [ISFP-A] 호기심 많은 예술가</span><br>\r\n");
      out.write("\t\t\t                        <img src=\"img/Team1_1.png\" alt=\"광민\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>DY [INFP-T] 열정적인 중재자</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/Team1_2.png\" alt=\"도연\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>JG [INTJ-A] 용의주도한 전략가</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/Team1_3.png\" alt=\"정균\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t                <div class=\"col-md-12 text-center inner-padding\">\r\n");
      out.write("\t\t                \t<div class=\"row\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>SH [INFJ-T] 선의의 옹호자</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/Team1_4.png\" alt=\"성호\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>HN [ESFP-A] 자유로운 영혼의 연예인</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/Team1_5.png\" alt=\"한녘\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='col-md-4'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>JH [ISTJ-T] 청렴결백한 논리주의자</span><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"img/Team1_6.jpg\" alt=\"정하\" width=\"200px\" height=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </section>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Bottom.jsp", out, false);
      out.write("\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
