/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-01 08:44:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.bit.utils.Singleton_Helper;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;

public final class memberlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("kr.or.bit.utils.Singleton_Helper");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Admin.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>Member List</title>\r\n");
      out.write("    \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Top.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"d-flex align-items-stretch\">\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Left.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"page-holder w-100 d-flex flex-wrap\">\r\n");
      out.write("        <div class=\"container-fluid px-xl-5\">\r\n");
      out.write("        ");

				Connection conn = null;
				PreparedStatement pstmt = null;
				ResultSet rs = null;
				
				try {
					conn = Singleton_Helper.getConnection("oracle");
					String sql = "select id,ip from koreamember";
					pstmt = conn.prepareStatement(sql);
					rs = pstmt.executeQuery();
			
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 table-padding\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card mb-5 mb-lg-0\">         \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h2 class=\"h6 mb-0 text-uppercase\">Member List</h2>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"text-gray\">회원관리하세요~</p>\r\n");
      out.write("\t\t\t\t\t\t\t<form id=\"searchForm\" class=\"ml-auto d-none d-lg-block mb-3\" action=\"memberSearch.jsp\" method=\"post\">\r\n");
      out.write("              \t\t\t\t\t<div class=\"form-group position-relative mb-0\">\r\n");
      out.write("                \t\t\t\t\t\t<button type=\"submit\" style=\"top: -3px; left: 0;\" class=\"position-absolute bg-white border-0 p-0\">\r\n");
      out.write("                \t\t\t\t\t\t<i class=\"o-search-magnify-1 text-gray text-lg\"></i></button>\r\n");
      out.write("                \t\t\t\t\t\t<input type=\"search\" name=\"search\" placeholder=\"회원명 Search ...\" class=\"form-control form-control-sm border-0 no-shadow pl-4\">\r\n");
      out.write("              \t\t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t</form>\r\n");
      out.write("\t\t\t");

					while(rs.next()){
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 회원리스트 1줄 -->\r\n");
      out.write("                    \t<div class=\"d-flex justify-content-between align-items-start align-items-sm-center mb-4 flex-column flex-sm-row\">\r\n");
      out.write("                      \t\t<div class=\"left d-flex align-items-center\">\r\n");
      out.write("                        \t\t<div class=\"icon icon-lg shadow mr-3 text-gray\"><i class=\"fab fa-android\"></i></div>\r\n");
      out.write("                        \t\t\t<div class=\"text\">\r\n");
      out.write("                          \t\t\t\t<h6 class=\"mb-0 d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span><a href='memberDetail.jsp?id=");
      out.print(rs.getString("id"));
      out.write('\'');
      out.write('>');
      out.print( rs.getString("id") );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-gray\">");
      out.print( rs.getString("ip") );
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"right ml-5 ml-sm-0 pl-3 pl-sm-0 text-violet\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='memberEdit.jsp?id=");
      out.print(rs.getString("id"));
      out.write("'><span>수정</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='memberDelete.jsp?id=");
      out.print(rs.getString("id"));
      out.write("'><span>삭제</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    \t<!-- 회원리스트 1줄 -->\r\n");
      out.write("\t\t\t");

					}
			
      out.write("\r\n");
      out.write("\t\t\t         </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div> \r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				} catch(Exception e){
					
				} finally{
					Singleton_Helper.close(rs);
					Singleton_Helper.close(pstmt);
				}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/Bottom.jsp", out, false);
      out.write("\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
