/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-10-28 07:55:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Boot_005fTemplate_005fMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "commonmodule/B_top.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"about\" class=\"section-padding1 text-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                    <div class=\"about-text wow bounceIn\">\r\n");
      out.write("                        <div class=\"about-icon\">\r\n");
      out.write("                            <i class=\"li_world\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <h2>민주주의인민공화국</h2>\r\n");
      out.write("                        <p>위대한 령도자 김정하 위원장 동지와 함께하는 력삼동 1호 JAVA 개발 위원회<br>\r\n");
      out.write("                            날때부터 응애응애 대신 'Java'라고 부르짖으며 탄생하신 김정하 위원장 동지의<br>\r\n");
      out.write("                            강제성이라곤 눈을 <del>찌르고</del> 씻고 찾아봐도 찾을 수 없는 민주적이고 결단력 있는 지도 아래,<br>\r\n");
      out.write("                            력삼동 1호 개발을 위한 영광스러운 고난의 행군을 하고있는 행복가득 1조입니다.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End about -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"testimonials\" class=\"section-dark\">\r\n");
      out.write("        <div data-velocity=\"-.3\" class=\"overlay-bg testimonial-bg\"></div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("                    <div id=\"testimonial-list\" class=\"carousel slide text-center\" data-ride=\"carousel\">\r\n");
      out.write("                        <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("                            <div class=\"item active\">\r\n");
      out.write("                                <div class=\"single-testimonial\">\r\n");
      out.write("                                    <i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("                                    <p>죽갓시오......<br>\r\n");
      out.write("                                       ㅠㅠ</p>\r\n");
      out.write("                                    <p class=\"author-name\">익명의 제보자</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <div class=\"single-testimonial\">\r\n");
      out.write("                                    <i class=\"fa fa-quote-left\"></i>\r\n");
      out.write("                                    <p>저리가요..<br>\r\n");
      out.write("                                       \t 행복한 척 해야하니까...ㅠㅠ</p>\r\n");
      out.write("                                    <p class=\"author-name\">익명의 제보자</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <a class=\"left tc-control\" href=\"#testimonial-list\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                        <i class=\"fa fa-angle-left\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a class=\"right tc-control\" href=\"#testimonial-list\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                        <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>    <!-- End testimonials -->   \r\n");
      out.write("    \r\n");
      out.write("    <section id=\"member\" class=\"section-padding\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8 col-md-offset-2 wow zoomIn\">\r\n");
      out.write("                    <div class=\"page-title text-center\">\r\n");
      out.write("                        <h2>Member</h2>\r\n");
      out.write("                        <p>행복이 오지는 이 곳, 아오지로 오세요</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("                       \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                    <div class=\"client-list wow zoomIn page-title\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                            <a href=\"member/gmkim/introduce.html\" target=\"_blank\"><img src=\"img/Team1_1.png\" alt=\"광민\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                        \t<a href=\"member/doyeon/index.html\" target=\"_blank\"><img src=\"img/Team1_2.png\" alt=\"도연\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                            <a href=\"member/JGKIm/index.html\" target=\"_blank\"><img src=\"img/Team1_3.png\" alt=\"정균\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                            <a href=\"member/psh/index_psh.html\" target=\"_blank\"><img src=\"img/Team1_4.png\" alt=\"성호\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                            <a href=\"member/khn/nyuck.html\" target=\"_blank\"><img src=\"img/Team1_5.png\" alt=\"한녘\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-client\">\r\n");
      out.write("                            <a href=\"member/kjh/Green.html\" target=\"_blank\"><img src=\"img/Team1_6.jpg\" alt=\"정하\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                    <div class=\"about-text wow bounceIn text-center page-title\">\r\n");
      out.write("                        <h3>MBTI</h3>\r\n");
      out.write("                        <p>● 김광민 : ISFP-A 호기심 많은 예술가 ● 임도연 : INFP-T  열정적인 중재자 ● 김정균 : INTJ-A 용의주도한 전략가<br>\r\n");
      out.write("                           ● 박성호 : INFJ-T 선의의 옹호자 ● 김한녘 : ESFP-A 자유로운 영혼의 연예인 ● 김정하 : ISTJ-T 청렴결백한 논리주의자\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                        <div class=\"about-text wow bounceIn text-center page-title\">\r\n");
      out.write("                            <a href=\"Team1_mbti/main.html\" target=\"_balck\"><h3>MBTI 결과는 여기서..</h3></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End our clients -->  \r\n");
      out.write("\r\n");
      out.write("    <section id=\"rolling\" class=\"section-padding section-gray\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8 col-md-offset-2 text-center wow zoomIn\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <h2>롤링페이퍼</h2>\r\n");
      out.write("                        <p></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>           \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"article-list wow zoomIn\">\r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                        \t<div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0001.jpg\" target=\"_blank\">김광민</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \t<div class=\"article-title\">\r\n");
      out.write("                            \t<a href=\"img/0001.jpg\" target=\"_blank\"><img src=\"img/face1.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                            <div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0002.jpg\" target=\"_blank\">김정균</a>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                            <div class=\"article-title\">\r\n");
      out.write("                                <a href=\"img/0002.jpg\" target=\"_blank\"><img src=\"img/face2.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                        \t<div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0003.jpg\" target=\"_blank\">김정하</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \t<div class=\"article-title\">\r\n");
      out.write("                            \t<a href=\"img/0003.jpg\" target=\"_blank\"><img src=\"img/face3.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                            <div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0004.jpg\" target=\"_blank\">김한녘</a>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                            <div class=\"article-title\">\r\n");
      out.write("                                <a href=\"img/0004.jpg\" target=\"_blank\"><img src=\"img/face4.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                        \t<div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0005.jpg\" target=\"_blank\">박성호</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \t<div class=\"article-title\">\r\n");
      out.write("                            \t<a href=\"img/0005.jpg\" target=\"_blank\"><img src=\"img/face5.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single-article\">\r\n");
      out.write("                            <div class=\"article-header\">\r\n");
      out.write("                                <a href=\"img/0006.jpg\" target=\"_blank\">임도연</a>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                            <div class=\"article-title\">\r\n");
      out.write("                                <a href=\"img/0006.jpg\" target=\"_blank\"><img src=\"img/face6.png\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End our blog -->\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"constellation\" class=\"section-padding2\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8 col-md-offset-2 text-center wow zoomIn\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <h2>별자리</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"single-event wow zoomIn\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-title\">\r\n");
      out.write("                                    <h2>인민들의 주거지입니다.</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"event-content\">\r\n");
      out.write("                                    <p>평화로운 민주주의인민공화국은 주거지에 제한이 없습니다.<br>원하는 지역에 거주할 수 있습니다.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-thumb\">\r\n");
      out.write("                                    <img src=\"img/event_1.png\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single-event wow zoomIn\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-thumb\">\r\n");
      out.write("                                    <img src=\"img/event_2.png\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                                       \r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-title\">\r\n");
      out.write("                                    <h2>인민들의 주거지를 선으로 이어봤습니다.</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"event-content\">\r\n");
      out.write("                                    <p>력삼동 1호 Bootstrap 개발 위원회 인민들은<br>모두 연결되어 있습니다.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"single-event wow zoomIn\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-title\">\r\n");
      out.write("                                    <h2>모두를 연결하면 돌고래자리가 됩니다.</h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"event-content\">\r\n");
      out.write("                                    <p></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <div class=\"event-thumb\">\r\n");
      out.write("                                    <img src=\"img/event_3.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End events -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <section id=\"more-events\" class=\"section-gray\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"old-event-list wow zoomIn\">\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                            <h2>묻고 웹으로 가!</h2>\r\n");
      out.write("                            <p>광민 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                            <h2>부트스트랩이 정말 어렵고 CSS는 더 어렵습니다…</h2>\r\n");
      out.write("                            <p>성호 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                            <h2>숫자와의 싸움에서 졌습니다</h2>\r\n");
      out.write("                            <p>한녘 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                            <h2><a href=\"\">적성에 안맞는거 같다..</a></h2>\r\n");
      out.write("                            <p>정하 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                            <h2><a href=\"\">오픈소스의 중요함과 java의 소중함을 알게되었습니다. 앞으로 자바 열심히 하겠습니다. ^^</a></h2>\r\n");
      out.write("                            <p>도연 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"single-old-event\">\r\n");
      out.write("                                <h2>논리적 사고가 필요했던 프로그래밍과는 전혀 다른 사고를 필요로 해서 당황스럽고 또 당황스러웠습니다.</h2>\r\n");
      out.write("                                <p>정균 / 2019 10 18</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End more events -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <section id=\"support\" class=\"section-padding1 text-center\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("                <div class=\"twitter-feed-wrapper wow zoomIn\">\r\n");
      out.write("                    <div class=\"twitter-feed-top\">\r\n");
      out.write("                        <i class=\"li_diamond\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("                    \t<button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\">당신의 조원에게 후원하세요.\r\n");
      out.write("                        <span class=\"caret\"></span></button>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                        \t<li><a href=\"member/gmkim/introduce.html\" target=\"_blank\">김광민 3333114271616 카카오뱅크</a></li>\r\n");
      out.write("                            <li><a href=\"member/doyeon/index.html\" target=\"_blank\">임도연 35390201140306 국민</a></li>\r\n");
      out.write("                            <li><a href=\"member/JGKIm/index.html\" target=\"_blank\">김정균 3020493782041 농협</a></li>\r\n");
      out.write("                            <li><a href=\"member/psh/index_psh.html\" target=\"_blank\">박성호 3561394314753 농협</a></li>\r\n");
      out.write("                            <li><a href=\"member/khn/nyuck.html\" target=\"_blank\">김한녘 3561390470463 농협</a></li>\r\n");
      out.write("                            <li><a href=\"member/kjh/Green.html\" target=\"_blank\">김정하 66550204105322 국민</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"single-twitter-feed\">\r\n");
      out.write("                        <img src=\"img/end.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> <!-- End twitter feed -->\r\n");
      out.write("    \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "commonmodule/B_foot.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
